version: '3.2'
services:
  bootnode:
    build:
      context: besu
      args:
        BESU_VERSION: ${BESU_VERSION}
    image: quickstart/besu:${BESU_VERSION}-privacy
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    entrypoint: /opt/besu/bootnode_start.sh --network=dev --min-gas-price=0
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}

  minernode:
    image: quickstart/besu:${BESU_VERSION}-privacy
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--miner-enabled",
              "--miner-coinbase=${MINER_COINBASE}",
              "--min-gas-price=0"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode

  orion1:
    build:
      context: orion
    image: quickstart/orion:${ORION_VERSION}
    entrypoint: /orion/bin/orion ${ORION_DATA_FOLDER1}/orion.conf
  orion2:
    image: quickstart/orion:${ORION_VERSION}
    entrypoint: /orion/bin/orion ${ORION_DATA_FOLDER2}/orion.conf
  orion3:
    image: quickstart/orion:${ORION_VERSION}
    entrypoint: /orion/bin/orion ${ORION_DATA_FOLDER3}/orion.conf

  node1:
    image: quickstart/besu:${BESU_VERSION}-privacy
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--privacy-enabled=true",
              "--privacy-url=${ORION_URL1}",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV",
              "--host-whitelist=*",
              "--min-gas-price=0",
              "--privacy-public-key-file=/etc/besu/privacy_public_key"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ${PWD}/besu/data1:/var/lib/besu
      - ${PWD}/orion/orion1:/etc/besu
    depends_on:
      - bootnode
      - orion1
    ports:
      - 20000:8545
      - 20001:8546

  node2:
    image: quickstart/besu:${BESU_VERSION}-privacy
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--privacy-enabled=true",
              "--privacy-url=${ORION_URL2}",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV",
              "--host-whitelist=*",
              "--min-gas-price=0",
              "--privacy-public-key-file=/etc/besu/privacy_public_key"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ${PWD}/besu/data2:/var/lib/besu
      - ${PWD}/orion/orion2:/etc/besu
    depends_on:
      - bootnode
      - orion2
    ports:
      - 20002:8545
      - 20003:8546
  node3:
    image: quickstart/besu:${BESU_VERSION}-privacy
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--privacy-enabled=true",
              "--privacy-url=${ORION_URL3}",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--rpc-http-api=EEA,WEB3,ETH,NET,PRIV",
              "--host-whitelist=*",
              "--min-gas-price=0",
              "--privacy-public-key-file=/etc/besu/privacy_public_key"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ${PWD}/orion/orion3:/etc/besu
      - ${PWD}/besu/data3:/var/lib/besu
    depends_on:
      - bootnode
      - orion3
    ports:
      - 20004:8545
      - 20005:8546

  rpcnode:
    image: quickstart/besu:${BESU_VERSION}-privacy
    command: ["--network=dev",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--host-whitelist=*",
              "--min-gas-price=0"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode
  explorer:
    build:
      context: ../block-explorer-light
      dockerfile: Dockerfile-privacy
    image: quickstart/block-explorer-light:${BESU_VERSION}-privacy
    depends_on:
      - rpcnode
    ports:
      - "${EXPLORER_PORT_MAPPING:-}80"
volumes:
  public-keys:
